
server:
  port: 8085
  
spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  rabbitmq:
    port: 5672
    host: ec2-3-128-80-159.us-east-2.compute.amazonaws.com
    username: guest2 
    password: "PvVf2pk&X9Xm%3"
     
  data:
    mongodb:
      uri: mongodb+srv://mongo_db:1992Andres_@tomcats.mhdmo.mongodb.net/forms?retryWrites=true&w=majority
      database: forms
      
  mail:
    protocol: smtp
    host: smtp.mailtrap.io
    port: 2525
    username: 2630cc7e4b74ae
    password: b464df1bb71bb2
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:file:~/test
#    username: sa
#   password:
#    driverClassName: org.h2.Driver

#  datasource:
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://localhost/postgres?
#    username: postgres
#    password: 1992Andres_