
server:
  port: ${custom_port:8087}
  
spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: "off"

  application:
    name: ${application_name:SurveyService}

  rabbitmq:
    host: ${rabbitmq_host}
    port: ${rabbitmq_port:5672}
    username: ${rabbitmq_username}
    password: ${rabbitmq_password}
    queue-listener: ${rabbitmq_queue_listener:FormResponse-Queue}

  data:
    mongodb:
      uri: ${mongodb_url:mongodb+srv://test123:MongoTest123!@cluster0.fs9sm.mongodb.net/test?retryWrites=true&w=majority}
      database: ${mongodb_database}
      
  mail:
    protocol: smtp
    host: ${mail_host}
    port: ${mail_port}
    username: ${mail_username}
    password: ${mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}

  instance:
    hostname: ${HOSTNAME:${spring.application.name}}
    preferIpAddress: false
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}:${server.port}


survey_service:
  scheduler_cron_pattern: ${scheduler_cron_pattern:0 0 10 * * MON}
  receiveEmailList_baseUrl: ${receiveEmailList_baseUrl:"http://localhost:8086"}
  receiveEmailList_endpoint: ${receiveEmailList_endpoint:"/associate/active-emails"}

  email_service:
    username: ${email_service_username}
    password: ${email_service_password}

  auth_service:
    secret: ${qcforce_token_secret:secret}

